import type { TeamLogo } from "@/types";

export interface LogoPreset {
  id: string;
  label: string;
  config: Omit<TeamLogo, "mode" | "imageUrl" | "teamName" | "displaySize">;
}

export const LOGO_PRESETS: LogoPreset[] = [
  {
    id: "yellow-navy-crest",
    label: "Yellow Navy Crest",
    config: {
      shape: "circle",
      borderStyle: "gold",
      backgroundStyle: "split",
      primaryColor: "#1e3a8a",
      secondaryColor: "#0f172a",
      accentColor: "#facc15",
      icon: "star",
      initials: "YN",
      showInitials: false,
      showIcon: true,
      showTeamName: false,
      textColor: "#fef9c3",
    },
  },
  {
    id: "red-yellow-lion",
    label: "Red Yellow Lion",
    config: {
      shape: "crest",
      borderStyle: "gold",
      backgroundStyle: "radial",
      primaryColor: "#dc2626",
      secondaryColor: "#7f1d1d",
      accentColor: "#fbbf24",
      icon: "lion",
      initials: "RL",
      showInitials: false,
      showIcon: true,
      showTeamName: false,
      textColor: "#ffffff",
    },
  },
  {
    id: "black-white-eagle",
    label: "Black White Eagle",
    config: {
      shape: "shield",
      borderStyle: "chrome",
      backgroundStyle: "split",
      primaryColor: "#f9fafb",
      secondaryColor: "#111827",
      accentColor: "#e5e7eb",
      icon: "eagle",
      initials: "BE",
      showInitials: false,
      showIcon: true,
      showTeamName: false,
      textColor: "#111827",
    },
  },
  {
    id: "claret-blue-storm",
    label: "Claret Blue Storm",
    config: {
      shape: "shield",
      borderStyle: "chrome",
      backgroundStyle: "gradient",
      primaryColor: "#7f1d1d",
      secondaryColor: "#1e3a8a",
      accentColor: "#93c5fd",
      icon: "lightning",
      initials: "CB",
      showInitials: true,
      showIcon: true,
      showTeamName: false,
      textColor: "#ffffff",
    },
  },
  {
    id: "green-crocodile",
    label: "Green Crocodile",
    config: {
      shape: "roundedShield",
      borderStyle: "chrome",
      backgroundStyle: "gradient",
      primaryColor: "#166534",
      secondaryColor: "#052e16",
      accentColor: "#86efac",
      icon: "claw",
      initials: "GC",
      showInitials: true,
      showIcon: true,
      showTeamName: false,
      textColor: "#ecfdf5",
    },
  },
  {
    id: "red-bull-crest",
    label: "Red Bull Crest",
    config: {
      shape: "crest",
      borderStyle: "chrome",
      backgroundStyle: "radial",
      primaryColor: "#dc2626",
      secondaryColor: "#0a0a0a",
      accentColor: "#fca5a5",
      icon: "bull",
      initials: "RB",
      showInitials: false,
      showIcon: true,
      showTeamName: false,
      textColor: "#ffffff",
    },
  },
  {
    id: "royal-crown",
    label: "Royal Crown",
    config: {
      shape: "hexagon",
      borderStyle: "gold",
      backgroundStyle: "radial",
      primaryColor: "#581c87",
      secondaryColor: "#1e1b4b",
      accentColor: "#fbbf24",
      icon: "crown",
      initials: "RC",
      showInitials: true,
      showIcon: true,
      showTeamName: false,
      textColor: "#fef3c7",
    },
  },
  {
    id: "fire-wolves",
    label: "Fire Wolves",
    config: {
      shape: "esports",
      borderStyle: "chrome",
      backgroundStyle: "gradient",
      primaryColor: "#0a0a0a",
      secondaryColor: "#431407",
      accentColor: "#fb923c",
      icon: "wolf",
      initials: "FW",
      showInitials: true,
      showIcon: true,
      showTeamName: false,
      textColor: "#ffedd5",
    },
  },
  {
    id: "storm-falcon",
    label: "Storm Falcon",
    config: {
      shape: "diamond",
      borderStyle: "neon",
      backgroundStyle: "radial",
      primaryColor: "#1e40af",
      secondaryColor: "#0f172a",
      accentColor: "#38bdf8",
      icon: "falcon",
      initials: "SF",
      showInitials: false,
      showIcon: true,
      showTeamName: false,
      textColor: "#e0f2fe",
    },
  },
  {
    id: "iron-spartan",
    label: "Iron Spartan",
    config: {
      shape: "pentagon",
      borderStyle: "triple",
      backgroundStyle: "solid",
      primaryColor: "#27272a",
      secondaryColor: "#09090b",
      accentColor: "#a1a1aa",
      icon: "spartan",
      initials: "IS",
      showInitials: true,
      showIcon: true,
      showTeamName: false,
      textColor: "#fafafa",
    },
  },
];

export function applyLogoPreset(
  preset: LogoPreset,
  current: TeamLogo,
  shortName: string
): TeamLogo {
  return {
    ...current,
    mode: "generated",
    presetId: undefined,
    imageUrl: undefined,
    teamName: shortName,
    ...preset.config,
  };
}
